language: python

env:
  global:
    - PIPENV_IGNORE_VIRTUALENVS=1

matrix:
  include:
    - python: 2.7
    - python: 3.6
    - python: 3.7     # see: https://github.com/travis-ci/travis-ci/issues/9815
      dist: xenial
      sudo: true

install:
  - pip install pipenv
  - pipenv install -e .

script:
  - ./tests.sh
