#!/usr/bin/env python
# coding: utf-8

import argparse
import errno
try:
    import simplejson as json
except ImportError:
    import json
import socket
import sys
import time

from collections import defaultdict


def inet_addr(arg):
    sfamily = socket.AF_INET
    host, port = arg.rsplit(':', 1)
    addr = (host, int(port))
    return sfamily, addr, host


def unix_addr(arg):
    sfamily = socket.AF_UNIX
    addr = arg
    return sfamily, addr, socket.gethostname()


def abstract_unix_addr(arg):
    sfamily = socket.AF_UNIX
    addr = '\0' + arg[1:]
    return sfamily, addr, socket.gethostname()


def run(stats, freq, node, role, f):
    if ':' in stats:
        sfamily, addr, host = inet_addr(stats)
    elif stats.startswith('@'):
        sfamily, addr, host = abstract_unix_addr(stats)
    else:
        sfamily, addr, host = unix_addr(stats)

    # RPS calculation
    first = True
    last_ts = time.time()
    last_req = defaultdict(int)

    while True:
        js = ''
        s = socket.socket(sfamily, socket.SOCK_STREAM)
        try:
            s.connect(addr)
            while True:
                data = s.recv(4096)
                if len(data) < 1:
                    break
                js += data.decode('utf8', 'ignore')
        except IOError as e:
            if e.errno != errno.EINTR:
                raise
            continue
        except:
            raise Exception("unable to get uWSGI statistics")
        finally:
            s.close()

        try:
            dd = json.loads(js)
        except json.JSONDecodeError:
            continue

        if 'workers' not in dd:
            raise Exception("unable to get uWSGI statistics")

        workers = dd['workers']

        result = dict()
        result['ver'] = dd.get('version', 'unknown')
        result['node'] = node
        result['role'] = role
        result['req'] = sum([w['requests'] for w in workers])

        _sum_avg = _sum_rss = _sum_vsz = 0

        dt = time.time() - last_ts
        for w in workers:
            # calculate rps
            w['rps'] = int(round((w['requests'] - last_req[w['id']]) / dt))
            last_req[w['id']] = w['requests']
            # sum to-be-averaged metrics
            _sum_avg += w['avg_rt']
            _sum_rss += w['rss']
            _sum_vsz += w['vsz']
        last_ts = time.time()

        # after reloading, rps maybe a negative number, set it to 0
        result['rps'] = max(0 if first else sum([w['rps'] for w in workers]), 0)
        first = False

        result['avg'] = round(_sum_avg / float(len(workers)) / 1000.0)
        result['lq'] = int(dd.get('listen_queue', 0))
        result['tx'] = sum([w['tx'] for w in workers])

        _status = [w['status'] for w in workers]
        result['busy'] = _status.count('busy')
        result['idle'] = len(_status) - result['busy']

        result['rss'] = int(_sum_rss / float(len(workers)))
        result['vsz'] = int(_sum_vsz / float(len(workers)))

        sys.stdout.write(f.strip().format(**result))
        sys.stdout.write('\n')
        sys.stdout.flush()

        time.sleep(freq)


def main():
    default_format = 'uwsgi,node={node},role={role} req={req}i,rps={rps}i,avg={avg},lq={lq}i,busy={busy}i,idle={idle}i,rss={rss}i'

    parser = argparse.ArgumentParser(formatter_class=argparse.RawTextHelpFormatter)
    parser.add_argument('--node', '-n', dest='node', default=socket.gethostname(), help='uWSGI node name, default: "{}"'.format(socket.gethostname()))
    parser.add_argument('--role', '-r', dest='role', default='uwsgi', help='uWSGI role name, default: "uwsgi"')
    parser.add_argument('--frequency', '-q', dest='freq', default=1, type=float, help='uWSGI stats refresh frequency, in seconds')
    parser.add_argument('--format', '-f', dest='format', default=default_format,
                        help='''output format, available variables:
    ver  - uWSGI version
    node - uWSGI node name
    role - uWSGI role name
    req  - total requests
    rps  - requests per second
    avg  - average response time
    lq   - listen queue
    busy - busy workers count
    idle - idle workers count
    rss  - average RSS (Resident Set Size)
    vsz  - average VSZ (Virtual Memory Size)

e.g. "{}"'''.format(default_format))

    parser.add_argument('stats', help='uWSGI stats address')

    args = parser.parse_args()

    try:
        run(stats=args.stats, freq=args.freq, node=args.node, role=args.role, f=args.format)
    except IOError as e:
        if e.errno == errno.EPIPE:
            sys.exit(0)


import signal
signal.signal(signal.SIGINT, lambda signal, frame: sys.exit(130))


if __name__ == '__main__':
    main()
